### ISSUE TITLE
Status is set to success in failed custom action

### ISSUE THREAD

**Issue by ylhan** [ravsamhq/notify-slack-action#111]
![image](https://github.com/ravsamhq/notify-slack-action/assets/23009089/25f19728-07f4-42f8-8253-987e530776e1)

You can see here that the previous steps failed however `notify-slack-action`'s status is set to `success` which causes it not to alert since I have notify-when failure set.

Here's my custom action:
```
name: "Safe Amazon ECS Deploy Task Definition"
description: 'Deploy an Amazon ECS task definition "safely" (verify that the deployment was not rolled back)'
inputs:
  service-name:
    description: "The name of the service being deployed"
    required: true
    type: string
  task-definition:
    description: "The task definition to deploy"
    required: true
    type: string
  cluster:
    description: "The cluster to deploy to"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      id: ecs-deploy
      with:
        task-definition: ${{ inputs.task-definition }}
        service: ${{ inputs.service-name }}
        cluster: ${{ inputs.cluster }}
        wait-for-service-stability: true
    - name: Check if deployment was successful
      id: check-deployment
      if: always()
      run: |
        CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ inputs.cluster }} --services ${{ inputs.service-name }} --query services[0].deployments[0].taskDefinition | jq -r ".")
        NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
        echo "Current task arn: $CURRENT_TASK_DEF_ARN"
        echo "New task arn: $NEW_TASK_DEF_ARN"
        if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
          echo "Deployment failed."
          exit 1
        fi
      shell: bash
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notification_title: "{workflow} has {status_message}"
        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> | <{run_url}|View Run>"
        footer: "Linked Repo <{repo_url}|{repo}>"
        # Only alert on failure to prevent spamming the channel
        notify_when: "failure"
```
