### ISSUE TITLE
Slack notification not being sent on success

### ISSUE THREAD

**Issue by SkylerWittman** [ravsamhq/notify-slack-action#121]
Hey there, 

I've got a custom action that the last step is to send a slack notification of our customer release. Here is the action in the GHA yml file:

```yaml
    - name: Slack customer deployment notification
      uses: ravsamhq/notify-slack-action@v1
      # Skip this notification for dev deployments
      if: ${{ !contains('["foo", "bar", "baz"]', inputs.clientName) }}
      with:
        status: ${{ job.status }}
        notification_title: "{repo} has been deployed to a customer environment"
        message_format: "Environment: '${{ inputs.clientName }}' has been deployed with version: `${{ inputs.imageTag }}`"
        notify_when: "success"
        icon_success: ":white_check_mark:"

      env:
        SLACK_WEBHOOK_URL: ${{ inputs.clientDeploymentSlackUrl }}
```

And I'm seeing all of those values correctly in the action when it ran:

```
Run ravsamhq/notify-slack-action@v1
  with:
    status: success
    notification_title: ***repo*** has been deployed to a customer environment
    message_format: Environment: 'foo' has been deployed with version: `v1.2.3`
    notify_when: success
    icon_success: :white_check_mark:
    footer: <***run_url***|View Run> | Developed by <https://www.ravsam.in|RavSam>
    mention_users_when: success,failure,warnings
    mention_groups_when: success,failure,warnings
    icon_failure: :x:
    icon_warnings: :large_orange_diamond:
  env:
    ENVIRONMENT_NAME: foo
    TAG_OR_COMMIT: v1.2.3
    VERSION: v1.2.3
    # ...
    SLACK_WEBHOOK_URL: ***
```

Obviously the `SLACK_WEBHOOK_URL` comes from a secret so it's not shown in the action output.

Is something wrong with the way I have it setup? Is there a way to debug this effectively to figure out why it failed?

Thanks!
