### ISSUE TITLE
Provide more documentation for usage

### ISSUE THREAD

**Issue by brno32** [ravsamhq/notify-slack-action#2]
Hello! I'm new to GitHub actions and I'm confused how this should be implemented. When I set it up per the sample repo, I got a notification that this action was checked out properly, but it didn't notify me about the actual workflow step I wanted to receive notifications for.

Would it be all right to request some more docs?

**Comment by ravgeetdhillon** [comment]
Hi @brno32, have you gone through this [blog post](https://www.ravsam.in/blog/send-slack-notification-when-github-actions-fails/)?
This can help you for sure. The main points are:

1. Create a Slack Bot and get a Webhook URL
2. Add this Webhook URL in Github Secrets as `ACTION_MONITORING_SLACK`
3. Then simply use the following step in your workflow
```yml
- name: Report Status
  if: always()
  uses: ravsamhq/notify-slack-action@master
  with:
    status: ${{ job.status }}
    notify_when: 'failure'
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
```

You can use `notify_when` input with any of the following values `'success,failure,warning'`. You can even use a combination of values.
