### ISSUE TITLE
Expose {actor} variable

### ISSUE THREAD

**Issue by davegallant** [ravsamhq/notify-slack-action#20]
It would be useful to have access to [GITHUB_ACTOR](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) to display the name of the person or app that initiated the workflow.

This is similar to a Slack User mention, however it is not always necessary to notify users under all circumstances.

**Comment by davegallant** [comment]
Alternatively, it's possible to get access to this variable by simply passing it in:

```yaml
- name: Notify Slack
  uses: ravsamhq/notify-slack-action@v1
  if: always()
  with:
    status: ${{ job.status }}
    token: ${{ secrets.GITHUB_TOKEN }}
    message_format: >
      ${{ env.GITHUB_ACTOR }} pushed <{commit_url}|{commit_sha}>


      ${{ github.event.head_commit.message }}
    notify_when: 'success'
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    GITHUB_ACTOR: ${{ github.actor }}
```

**Comment by davegallant** [comment]
Actually, it seems simpler to just use GitHub's expression syntax:

```yaml
- name: Notify Slack
  uses: ravsamhq/notify-slack-action@v1
  if: always()
  with:
    status: ${{ job.status }}
    token: ${{ secrets.GITHUB_TOKEN }}
    message_format: >
      ${{ github.actor }} pushed <{commit_url}|{commit_sha}>
    notify_when: 'success'
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```
