### ISSUE TITLE
Using @channel for notifications

### ISSUE THREAD

**Issue by DanielHHowell** [ravsamhq/notify-slack-action#28]
Hi, I have the following 

```
      - name: Report Status Failure
        uses: ravsamhq/notify-slack-action@v1
        if: failure()
        with:
          status: ${{ job.status }}
          notification_title: '@channel {workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> - <{run_url}|View Run>'
          footer: 'Linked Repo <{repo_url}|{repo}>'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

that just pastes raw "@channel" rather than actually notifiying. I followed this [issue](https://github.com/ravsamhq/notify-slack-action/issues/16) to attempt to get it to work right but still no success

**Comment by ravgeetdhillon** [comment]
I think @ won't work in titles. Try using them in `message_format` parameter.
Let me know if this works for you.

**Comment by DanielHHowell** [comment]
Thanks for the quick reply. I had tried that previously like:

```
      - name: Report Status Failure
        uses: ravsamhq/notify-slack-action@v1
        if: failure()
        with:
          status: ${{ job.status }}
          notification_title: '{workflow} has {status_message}'
          message_format: '@channel {emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> - <{run_url}|View Run>'
          footer: 'Linked Repo <{repo_url}|{repo}>'
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

but also sent the @channel as raw
