### ISSUE TITLE
Can the slack notification show git tag, commit author, and commit message?

### ISSUE THREAD

**Issue by IgorGov** [ravsamhq/notify-slack-action#29]

**Comment by ravgeetdhillon** [comment]
Hey @IgorGov ,

Here is what you can do:

1. Add the following step to get all the information related to your Github context
```yml
steps:
  - run: echo "${{ toJson(github) }}"
```

2. Then you can use reference the `github` object properties:
```
github.event.head_commit.author.name
github.event.head_commit.message
```

as

```yml
steps:
  - uses: ravsamhq/notify-slack-action@v1
    if: always()
    with:
      ...
      message_format: '{emoji} ${{ github.event.head_commit.author.name }} ${{ github.event.head_commit.message }}'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

Let me know if this helps you.
