### ISSUE TITLE
Is it possible to change the emoji_icon?

### ISSUE THREAD

**Issue by ksafranski** [ravsamhq/notify-slack-action#30]
Love this action, only thing is it defaults to whatever slack has set for the avatar/emoji_icon. Is there a way to set that currently?

**Comment by smetroid** [comment]
@ksafranski if you have the ability/permissions you can chance the avatar/emoji_icon in the slack webhook configuration.

**Comment by ravgeetdhillon** [comment]
Hey @ksafranski,

This feature has been added to release [1.7.0](https://github.com/ravsamhq/notify-slack-action/releases/tag/1.7.0).

You can now customize the action emojis based on the status event:

```yml
steps:
  - uses: ravsamhq/notify-slack-action@v1
    if: always()
    with:
      status: ${{ job.status }}
      ...
      icon_success: ':heavy_check_mark:'
      icon_failure: ':x:'
      icon_warnings: ':large_orange_diamond:'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

Let me know if this solves your issue.
