### ISSUE TITLE
Ability to print the "name" property of the job

### ISSUE THREAD

**Issue by jay-cresta** [ravsamhq/notify-slack-action#36]
We have reusable job which runs on different parameters and also the name of the job is generated dynamically.

```
jobs:
  test:
    name: Run ${{ inputs.param1 }} tests on ${{ inputs.param2 }}
    runs-on: ubuntu-latest
```

With a job setup something lie this, the name always prints as "test" in the slack notification instead of the name generated at runtime

![image](https://user-images.githubusercontent.com/88337424/152518140-976f1397-a447-4ce6-99b1-d7522e0c34dc.png)

**Comment by ravgeetdhillon** [comment]
@jay-cresta The name of the job is `test`. You are dynamically generating the name of the step. There is no way to define a job name dynamically.

**Comment by jay-cresta** [comment]
@ravgeetdhillon Sorry for the confusion caused because of partial code snippet. Actually that is the name property of the job (can be called description) and is not part of the steps. See below..

```
jobs:
  test:
    name: Run ${{ inputs.param1 }} tests on ${{ inputs.param2 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies 
        run: |
          npm i
      
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
```

Is there a way to show the name property of the job?
Thanks a ton!
