### ISSUE TITLE
Is there a way to enable caching?

### ISSUE THREAD

**Issue by kary-ajrj** [ravsamhq/notify-slack-action#47]
<img width="1038" alt="Screenshot 2022-06-08 at 17 36 55" src="https://user-images.githubusercontent.com/7961532/172612687-18941764-24c9-42d2-9a3f-5c70503dc322.png">

This step (above) takes 16 seconds each time the Github Action is run.
If caching is enabled then this time is likely to reduce drastically.

Example:
```
- uses: actions/setup-node@v3
   with:
      node-version: '16.15.1'
      cache: 'yarn'
```

Kindly let us know if it possible already or if it can be put in place.
