### ISSUE TITLE
Git commit message as oneline

### ISSUE THREAD

**Issue by ndench** [ravsamhq/notify-slack-action#57]
Thanks for the great GitHub Action! I was able to get it up and running immediately on the first try!

From the docs I know that we can get the git commit message as `${{ github.event.head_commit.message }}`, but I was wondering if there's a way that we can get just the first line of the commit message? 

Also, as an FYI, the `head_commit.message` property only exists on some workflow payloads. You might have to access it differently depending on how the workflow is triggered. Might be worth adding at link to the [Workflow Payload doc](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads) in the README?

**Comment by ravgeetdhillon** [comment]
@ndench These are some of the [functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions) that are available in GitHub Actions but I don't think there is one that can help you solve your problem.

You can write a bash script to get the first line of the commit message `${{ github.event.head_commit.message }}`, store it in a variable and then reference it in the `notify-slack` action message.

**Comment by ndench** [comment]
Great, thanks for the tip @ravgeetdhillon. For anyone else looking for this, I've managed to get it working with the following. 
NOTE: I'm triggering the workflow using the `workflow_run` event, not `pull_request`.

```yaml
            - name: Get commit message
              if: always()
              id: commit
              run: echo "::set-output name=message::$(echo '${{ github.event.workflow_run.head_commit.message }}' | head -n 1)"
            - name: Send slack notification
              uses: ravsamhq/notify-slack-action@v2
              if: always()
              with:
                  message_format: '{emoji} ${{ steps.commit.message }}'
                  footer: "<{commit_url}|{repo}> | <{run_url}|{workflow}>"
                  token: ${{ secrets.GITHUB_TOKEN }}
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

```
