### ISSUE TITLE
Error: No SLACK_WEBHOOK_URL provided after upgrading to v2?

### ISSUE THREAD

**Issue by spokenbird** [ravsamhq/notify-slack-action#62]
Hello,

I just upgraded to ravsamhq/notify-slack-action@v2 and am now seeing failures in the announce to slack action with the error thrown reading: Error: No SLACK_WEBHOOK_URL

We are however providing a SLACK_WEBHOOK_URL as seen in our config below:

```
- name: Announce on Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

Might you be able to provide any insights?
![Screen Shot 2022-09-09 at 4 05 33 PM](https://user-images.githubusercontent.com/39173486/189457310-e6566f38-bf37-4d8f-92fa-0404d600fb05.png)
