### ISSUE TITLE
Feature request: Notify user who made commit

### ISSUE THREAD

**Issue by niels-bosman** [ravsamhq/notify-slack-action#72]
Right now you can notify slack users for when the pipeline fails, would be nice if there was an option to map the GitHub users with the Slack username so only the person committing get's tagged in the message.

**Comment by ravgeetdhillon** [comment]
@niels-bosman @rdhar Do you have any suggestions on how you would like this to be implemented from the end user perspective?

**Comment by niels-bosman** [comment]
@ravgeetdhillon @rdhar I think it should be easy for users to enable this behaviour. The more complex logic should be dealt with by the package itself. Something like this:

```yaml
steps:
  - uses: ravsamhq/notify-slack-action@v2
    if: always()
    with:
      status: ${{ job.status }}
      notify_actor: true # The new field
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
```
