### ISSUE TITLE
Add the possibility to access to job name (versus job id)

### ISSUE THREAD

**Issue by lbesson-della** [ravsamhq/notify-slack-action#93]
Currently `{job}` only allows to access a job id.
Can we have access to a job's name?

For example if we have:
```yaml
jobs:
  jobid:
    name: 'Job friendly name'
```
`{job}` will return `jobid`
