### ISSUE TITLE
Canceled runs are notified as "passed with warnings"

### ISSUE THREAD

**Issue by wookayin** [ravsamhq/notify-slack-action#99]
I'm using notify-slack-action@v2. When I manually interrupt or cancel the workflow, a **wrong** notification is made saying the job has been passed with warnings. It should instead say something like the job was cancelled or failed.

```
:large_orange_diamond: Run Tests passed with warnings in
```

```
      - name: Report status to Slack
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure,cancelled"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_NOTIFICATION_SLACK }}
```
